name: mdlm
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - cuda-nvcc=12.4.99
  - jupyter=1.0.0
  - pip=23.3.1
  - python=3.11
  - pytorch-cuda=12.1
  - pip:
    # Please ignore any warnings while installing the dependencies
    -  torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu121
    -  datasets
    -  einops==0.7.0
    -  fsspec
    -  git-lfs==1.6
    -  h5py
    -  hydra-core==1.3.2
    -  lightning==2.2.1
    -  nvitop==1.3.2
    -  omegaconf==2.3.0
    -  packaging==23.2
    -  pandas
    -  rich==13.7.1
    -  seaborn==0.13.2
    -  scikit-learn==1.4.0
    -  timm==0.9.16
    -  transformers==4.38.2
    -  triton
    -  wandb==0.13.5
    -  flash-attn==2.5.6 # NOTE: The HF model employed in Colab does not utilize Flash Attention, and all intermediate computations are performed in fp32 
                         #  the T4 GPU on Google Colab does not support Flash Attention.
    -  causal-conv1d==1.1.3.post1
    -  mamba-ssm==1.1.4
    # pip uninstall -y torchao
    # pip uninstall -y numpy
    -  numpy==1.26.4